version: '3.8'

services:
  mediamtx-transcoder:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: phantomeye_webrtc_transcoder
    network_mode: host
    env_file:
      - .env
    environment:
      - MTX_WEBRTC=yes
      - MTX_WEBRTCADDRESS=:8889
      - MTX_RTSP=yes
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    restart: unless-stopped
